language: java
jdk:
  - oraclejdk11

before_install:
  - java -version
  - mvn --version
  - chmod +x mvnw

script: "mvn clean install"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker build -t linksmart/sensorthings-provisioning:latest . && docker push linksmart/sensorthings-provisioning:latest
    on:
      branch: master
