sudo: false
language: java
services:
- docker

install:
- provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean install"

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker build -t linksmart/sensorthings-provisioning:latest . && docker push linksmart/sensorthings-provisioning:latest
    on:
      branch: master
