language: java
jdk:
  - oraclejdk11

before_install:
  - "java -version"
  - "mvn --version"
  - "chmod +x mvnw"

before_deploy:
  - "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
  - "docker build -t linksmart/sensorthings-provisioning:latest ."
  - "docker images"
deploy:
  - provider: script
    docker push linksmart/sensorthings-provisioning:latest
    on:
      branch: master
